- name: app-setup
  ansible.builtin.import_role:
   name: common
   tasks_from: app-setup

- name: python
  ansible.builtin.import_role:
   name: common
   tasks_from: python

- name: systemmd setup
  ansible.builtin.import_role:
   name: common
   tasks_from: systemmd
