- name: Copy mongodb repo
  ansible.builtin.copy:
    src: mongodb.repo
    dest: /etc/yum.repos.d/mongodb.repo
- name: Install mongodb client
  package:
    name: mongodb-org-shell
    state: present
- name: "get the catalogue entries count"
  command: mongo --host mongodb.reddy1229.online --quiet --eval 'db = db.getSiblingDB("catalogue"); db.products.count()'
  register: product_count
  when: component == "catalogue"

- name: "get the user entries count"
  command: mongo --host mongodb.reddy1229.online --quiet --eval 'db = db.getSiblingDB("users"); db.users.count()'
  register: user_count
  when: component == "user"

# - name: print product count
#   debug: 
#    msg: "product count: {{product_count}}"

- name: "Load catalogue data"
  command: "mongo --host mongodb.reddy1229.online < /app/schema/{{component}}.js"
  when: product_count.stdout == "0" and component == "catalogue" #keep double quote
  ignore_errors: true 

- name: "Load user data"
  command: "mongo --host mongodb.reddy1229.online < /app/schema/{{component}}.js"
  when: user_count.stdout == "0" and component == "user" #keep double quote
  ignore_errors: true
