- name: Install mysql client
  dnf:
    name: mysql
    state: present
- name: check cities schema exists or not
  command: mysql -h {{MYSQL_HOST}}e -uroot -p{{mysql_password}} -sN -e "SELECT COUNT(*) FROM INFORMATION_SCHEMA.SCHEMATA WHERE SCHEMA_NAME = 'cities'"
  register: schema
- name: print output
  debug:
    msg: "Schema output: {{schema}}"
- name: load cities data
  shell: "mysql -h {{MYSQL_HOST}} -uroot -p{{mysql_password}}  < /app/schema/shipping.sql"
  when: schema.stdout != "1"
